name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
    # Optional: Only run on specific file changes
    # paths:
    #   - "src/**/*.ts"
    #   - "src/**/*.tsx"
    #   - "src/**/*.js"
    #   - "src/**/*.jsx"

jobs:
  claude-review:
    # Only allow repository owner to trigger Claude Code Review
    if: github.event.pull_request.user.login == 'qnaiv'
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    
    steps:
      - name: Verify owner access
        run: |
          echo "PR created by: ${{ github.event.pull_request.user.login }}"
          if [ "${{ github.event.pull_request.user.login }}" != "qnaiv" ]; then
            echo "❌ Unauthorized Claude Code Review attempt by ${{ github.event.pull_request.user.login }}"
            echo "Only the repository owner (qnaiv) can trigger Claude Code Review."
            exit 1
          fi
          echo "✅ Claude Code Review authorized for owner: ${{ github.event.pull_request.user.login }}"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4)
          # model: "claude-opus-4-20250514"
          
          # Direct prompt for automated review (no @claude mention needed)
          direct_prompt: |
            このプルリクエストを日本語でレビューしてフィードバックを提供してください：
            - コードの品質とベストプラクティス
            - 潜在的なバグや問題
            - パフォーマンスの考慮事項
            - セキュリティの懸念事項
            - テストカバレッジ
            
            建設的で有用なフィードバックを日本語で提供してください。
            
          # Custom instructions for Japanese responses
          custom_instructions: |
            必ず日本語で回答してください。
            コミットメッセージやプルリクエストの内容はすべて日本語で記載してください。
            GitHub flowに則って開発を行ってください。
            コードレビューのコメントも日本語で行ってください。

          # Optional: Use sticky comments to make Claude reuse the same comment on subsequent pushes to the same PR
          # use_sticky_comment: true
          
          # Optional: Customize review based on file types
          # direct_prompt: |
          #   Review this PR focusing on:
          #   - For TypeScript files: Type safety and proper interface usage
          #   - For API endpoints: Security, input validation, and error handling
          #   - For React components: Performance, accessibility, and best practices
          #   - For tests: Coverage, edge cases, and test quality
          
          # Optional: Different prompts for different authors
          # direct_prompt: |
          #   ${{ github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR' && 
          #   'Welcome! Please review this PR from a first-time contributor. Be encouraging and provide detailed explanations for any suggestions.' ||
          #   'Please provide a thorough code review focusing on our coding standards and best practices.' }}
          
          # Optional: Add specific tools for running tests or linting
          # allowed_tools: "Bash(npm run test),Bash(npm run lint),Bash(npm run typecheck)"
          
          # Optional: Skip review for certain conditions
          # if: |
          #   !contains(github.event.pull_request.title, '[skip-review]') &&
          #   !contains(github.event.pull_request.title, '[WIP]')

